{% set name = "datamodel-code-generator" %}
{% set version = "0.28.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datamodel_code_generator-{{ version }}.tar.gz
  sha256: ae1056643cf3cdd298ef4b622085158ec7ef1722f6da1c20e7022c942f2e3ebb

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - datamodel-codegen=datamodel_code_generator.__main__:main

requirements:
  host:
    - pip
    - hatchling >=1.25
    - hatch-vcs >=0.4
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - argcomplete >=2.10.1,<4
    - black >=19.10b0
    - genson >=1.2.1,<2
    - graphql-core >=3.2.3
    - httpx >=0.24.1
    - inflect >=4.1,<6
    - isort >=4.3.21,<7
    - jinja2 >=2.10.1,<4
    - openapi-spec-validator >=0.2.8,<0.7
    - packaging
    - prance >=0.18.2
    - pydantic >=1.5
    - pysnooper >=0.4.1,<2
    - pyyaml >=6.0.1
    - tomli >=2.2.1,<3

test:
  imports:
    - datamodel_code_generator
  commands:
    - pip check
    - datamodel-codegen --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/koxudaxi/datamodel-code-generator
  doc_url: https://koxudaxi.github.io/datamodel-code-generator/
  summary: Pydantic model and dataclasses.dataclass generator for easy conversion of JSON, OpenAPI, JSON Schema, and YAML data sources.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
