schema_version: 1

context:
  name: datamodel-code-generator
  version: "0.31.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/datamodel_code_generator-${{ version }}.tar.gz
  sha256: 85a5d5b5f7af2dc307a28ceff4ac3630ffbb297c6ec91937e1899f26a0dc2147

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - datamodel-codegen=datamodel_code_generator.__main__:main

requirements:
  host:
    - pip
    - hatchling >=1.25
    - hatch-vcs >=0.4
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - argcomplete >=2.10.1,<4
    - black >=19.10b0
    - genson >=1.2.1,<2
    - inflect >=4.1,<8
    - isort >=4.3.21,<7
    - jinja2 >=2.10.1,<4
    - packaging
    - pydantic >=1.5
    - pyyaml >=6.0.1
    - tomli >=2.2.1,<3

tests:
  - python:
      imports:
        - datamodel_code_generator
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - datamodel-codegen --help

about:
  summary: Pydantic model and dataclasses.dataclass generator for easy conversion of JSON, OpenAPI, JSON Schema, and YAML data sources.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/koxudaxi/datamodel-code-generator
  documentation: https://koxudaxi.github.io/datamodel-code-generator/

extra:
  recipe-maintainers:
    - thewchan
